# Generated by Django 5.2 on 2025-07-12 17:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Erkak'), ('Female', 'Ayol')], default='Male', max_length=50)),
                ('education', models.CharField(choices=[('3', 'O‘rta-maxsus'), ('4', 'Tuganlanmagan oliy'), ('5', 'Boshlang‘ich'), ('1', 'Oliy'), ('2', 'O‘rta')], default='1', max_length=50)),
                ('birth_date', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('passport', models.CharField(choices=[('drivers_license', 'Haydovchilik guvohnomasi'), ('old_pass', 'Eski turdagi passport'), ('id', 'ID passport')], default='id', max_length=50)),
                ('passport_serial', models.CharField(max_length=5)),
                ('passport_serial_number', models.CharField(max_length=10)),
                ('passport_address', models.CharField(max_length=50)),
                ('passport_jshshir', models.CharField(max_length=50)),
                ('passport_expiry', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.filial')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('pay_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('status', models.CharField(choices=[('pending', 'jarayonda'), ('rejected', 'rad etildi'), ('done', 'berildi')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lisa.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
