# Generated by Django 5.2 on 2025-07-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='passport_jshshir',
            new_name='passport_pinfl',
        ),
        migrations.AlterField(
            model_name='client',
            name='education',
            field=models.CharField(choices=[('5', 'Boshlang‘ich'), ('3', 'O‘rta-maxsus'), ('1', 'Oliy'), ('2', 'O‘rta'), ('4', 'Tuganlanmagan oliy')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Female', 'Ayol'), ('Male', 'Erkak')], default='Male', max_length=50),
        ),
    ]
