# Generated by Django 5.2 on 2025-07-12 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0002_rename_passport_jshshir_client_passport_pinfl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lisa.application'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='education',
            field=models.CharField(choices=[('4', 'Tuganlanmagan oliy'), ('2', 'O‘rta'), ('1', 'Oliy'), ('3', 'O‘rta-maxsus'), ('5', 'Boshlang‘ich')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.CharField(choices=[('old_pass', 'Eski turdagi passport'), ('drivers_license', 'Haydovchilik guvohnomasi'), ('id', 'ID passport')], default='id', max_length=50),
        ),
        migrations.AlterField(
            model_name='credit',
            name='status',
            field=models.CharField(choices=[('done', 'berildi'), ('pending', 'jarayonda'), ('rejected', 'rad etildi')], default='pending', max_length=50),
        ),
    ]
