# Generated by Django 5.2 on 2025-07-12 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0003_credit_application_alter_client_education_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='filial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.filial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='education',
            field=models.CharField(choices=[('1', 'Oliy'), ('5', 'Boshlang‘ich'), ('4', 'Tuganlanmagan oliy'), ('3', 'O‘rta-maxsus'), ('2', 'O‘rta')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Male', 'Erkak'), ('Female', 'Ayol')], default='Male', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.CharField(choices=[('drivers_license', 'Haydovchilik guvohnomasi'), ('id', 'ID passport'), ('old_pass', 'Eski turdagi passport')], default='id', max_length=50),
        ),
    ]
