# Generated by Django 5.2 on 2025-07-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0005_alter_client_education_alter_client_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='education',
            field=models.CharField(choices=[('5', 'Boshlang‘ich'), ('2', 'O‘rta'), ('1', 'Oliy'), ('4', 'Tuganlanmagan oliy'), ('3', 'O‘rta-maxsus')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.CharField(choices=[('old_pass', 'Eski turdagi passport'), ('drivers_license', 'Haydovchilik guvohnomasi'), ('id', 'ID passport')], default='id', max_length=50),
        ),
        migrations.AlterField(
            model_name='credit',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='status',
            field=models.CharField(choices=[('rejected', 'rad etildi'), ('done', 'berildi'), ('pending', 'jarayonda')], default='pending', max_length=50),
        ),
    ]
