# Generated by Django 5.2.4 on 2025-07-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0007_alter_client_address_alter_client_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='passport_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='education',
            field=models.CharField(choices=[('4', 'Tuganlanmagan oliy'), ('3', 'O‘rta-maxsus'), ('5', 'Boshlang‘ich'), ('2', 'O‘rta'), ('1', 'Oliy')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Male', 'Erkak'), ('Female', 'Ayol')], default='Male', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.CharField(blank=True, choices=[('old_pass', 'Eski turdagi passport'), ('id', 'ID passport'), ('drivers_license', 'Haydovchilik guvohnomasi')], default='id', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='status',
            field=models.CharField(choices=[('done', 'berildi'), ('pending', 'jarayonda'), ('rejected', 'rad etildi')], default='pending', max_length=50),
        ),
    ]
