# Generated by Django 5.2.4 on 2025-07-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0008_client_passport_city_client_passport_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='passport_got',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_got_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='education',
            field=models.CharField(choices=[('3', 'O‘rta-maxsus'), ('1', 'Oliy'), ('2', 'O‘rta'), ('5', 'Boshlang‘ich'), ('4', 'Tuganlanmagan oliy')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.CharField(blank=True, choices=[('drivers_license', 'Haydovchilik guvohnomasi'), ('old_pass', 'Eski turdagi passport'), ('id', 'ID passport')], default='id', max_length=50, null=True),
        ),
    ]
