# Generated by Django 5.2.4 on 2025-07-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0009_client_passport_got_client_passport_got_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='max_month',
            field=models.IntegerField(default=56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='rate',
            field=models.IntegerField(default=56),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='education',
            field=models.CharField(choices=[('4', 'Tuganlanmagan oliy'), ('2', 'O‘rta'), ('3', 'O‘rta-maxsus'), ('5', 'Boshlang‘ich'), ('1', 'Oliy')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Female', 'Ayol'), ('Male', 'Erkak')], default='Male', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.CharField(blank=True, choices=[('old_pass', 'Eski turdagi passport'), ('id', 'ID passport'), ('drivers_license', 'Haydovchilik guvohnomasi')], default='id', max_length=50, null=True),
        ),
    ]
