# Generated by Django 5.2.4 on 2025-07-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0010_application_max_month_application_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='education',
            field=models.CharField(choices=[('5', 'Boshlang‘ich'), ('2', 'O‘rta'), ('4', 'Tuganlanmagan oliy'), ('1', 'Oliy'), ('3', 'O‘rta-maxsus')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.CharField(blank=True, choices=[('id', 'ID passport'), ('drivers_license', 'Haydovchilik guvohnomasi'), ('old_pass', 'Eski turdagi passport')], default='id', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='credit',
            name='status',
            field=models.CharField(choices=[('done', 'berildi'), ('rejected', 'rad etildi'), ('pending', 'jarayonda')], default='pending', max_length=50),
        ),
    ]
