# Generated by Django 5.2.4 on 2025-07-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0011_alter_client_education_alter_client_passport_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='address',
            new_name='base_address',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='passport_address',
            new_name='base_city',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='passport_city',
            new_name='base_country',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='passport_region',
            new_name='base_region',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='passport_expiry',
            new_name='passport_expiry_date',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='passport_got',
            new_name='passport_got_date',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='passport_serial',
            new_name='passport_serial_letter',
        ),
        migrations.RemoveField(
            model_name='client',
            name='passport',
        ),
        migrations.AddField(
            model_name='client',
            name='current_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='current_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='current_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='current_region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_type',
            field=models.CharField(blank=True, choices=[('old_pass', 'Eski turdagi passport'), ('id', 'ID passport'), ('drivers_license', 'Haydovchilik guvohnomasi')], default='id', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='education',
            field=models.CharField(choices=[('5', 'Boshlang‘ich'), ('3', 'O‘rta-maxsus'), ('2', 'O‘rta'), ('1', 'Oliy'), ('4', 'Tuganlanmagan oliy')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='credit',
            name='status',
            field=models.CharField(choices=[('done', 'berildi'), ('pending', 'jarayonda'), ('rejected', 'rad etildi')], default='pending', max_length=50),
        ),
    ]
