# Generated by Django 5.2.4 on 2025-07-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0012_rename_address_client_base_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='country',
            new_name='client_country',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='region',
            new_name='client_region',
        ),
        migrations.AlterField(
            model_name='client',
            name='education',
            field=models.CharField(choices=[('5', 'Boshlang‘ich'), ('2', 'O‘rta'), ('4', 'Tuganlanmagan oliy'), ('1', 'Oliy'), ('3', 'O‘rta-maxsus')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Male', 'Erkak'), ('Female', 'Ayol')], default='Male', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_type',
            field=models.CharField(blank=True, choices=[('drivers_license', 'Haydovchilik guvohnomasi'), ('id', 'ID passport'), ('old_pass', 'Eski turdagi passport')], default='id', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='status',
            field=models.CharField(choices=[('rejected', 'rad etildi'), ('pending', 'jarayonda'), ('done', 'berildi')], default='pending', max_length=50),
        ),
    ]
