# Generated by Django 5.2.4 on 2025-07-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0013_rename_country_client_client_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='education',
            field=models.CharField(choices=[('5', 'Boshlang‘ich'), ('3', 'O‘rta-maxsus'), ('2', 'O‘rta'), ('4', 'Tuganlanmagan oliy'), ('1', 'Oliy')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], default='male', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_type',
            field=models.CharField(blank=True, choices=[('id', 'ID passport'), ('old_pass', 'Eski turdagi passport'), ('drivers_license', 'Haydovchilik guvohnomasi')], default='id', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='status',
            field=models.CharField(choices=[('pending', 'jarayonda'), ('done', 'berildi'), ('rejected', 'rad etildi')], default='pending', max_length=50),
        ),
    ]
