# Generated by Django 5.2.4 on 2025-07-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0015_alter_client_education_alter_client_passport_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='education',
            field=models.CharField(choices=[('1', 'Oliy'), ('2', 'O‘rta'), ('4', 'Tuganlanmagan oliy'), ('3', 'O‘rta-maxsus'), ('5', 'Boshlang‘ich')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_type',
            field=models.CharField(blank=True, choices=[('drivers_license', 'Haydovchilik guvohnomasi'), ('old_pass', 'Eski turdagi passport'), ('id', 'ID passport')], default='id', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='status',
            field=models.CharField(choices=[('pending', 'jarayonda'), ('done', 'berildi'), ('rejected', 'rad etildi')], default='pending', max_length=50),
        ),
    ]
