# Generated by Django 5.2.4 on 2025-07-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0017_alter_client_education_alter_client_passport_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='education',
            field=models.CharField(choices=[('1', 'Oliy'), ('2', 'O‘rta'), ('3', 'O‘rta-maxsus'), ('4', 'Tuganlanmagan oliy'), ('5', 'Boshlang‘ich')], default='2', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_type',
            field=models.CharField(blank=True, choices=[('id', 'ID passport'), ('old_pass', 'Eski turdagi passport'), ('drivers_license', 'Haydovchilik guvohnomasi')], default='id', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='status',
            field=models.CharField(choices=[('done', 'berildi'), ('rejected', 'rad etildi'), ('pending', 'jarayonda')], default='pending', max_length=50),
        ),
    ]
