# Generated by Django 5.2.5 on 2025-09-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0018_alter_client_education_alter_client_passport_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
