# Generated by Django 5.2.5 on 2025-09-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0020_alter_credit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='fine',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='limit_amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
