# Generated by Django 5.2.5 on 2025-09-08 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0021_application_fine_alter_application_limit_amount'),
        ('users', '0002_user_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lisa.application'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lisa.client'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.filial'),
        ),
    ]
