# Generated by Django 5.2.5 on 2025-09-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0022_alter_credit_application_alter_credit_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passport_pinfl',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
