# Generated by Django 5.2.5 on 2025-09-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0024_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
