# Generated by Django 5.2.5 on 2025-09-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0025_credit_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
