# Generated by Django 5.2.5 on 2025-09-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0026_alter_credit_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='status',
            field=models.CharField(choices=[('done', 'berildi'), ('rejected', 'rad etildi'), ('pending', 'jarayonda'), ('paid', 'yopilgan')], default='pending', max_length=50),
        ),
    ]
